version: '3.4'

services:
  api:
    container_name: api-product
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 7006:80
    depends_on:
      db-mongo:
        condition: service_started
      db-postgres:
        condition: service_started

  db-mongo:
    container_name: db-mongo-product
    image: mongo:latest
    ports:
      - 7017:27017

  db-postgres:
    container_name: db-postgres-product
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
    # volumes:
    #   - postgres-data:/var/lib/postgressql/data

volumes:
  postgres-data:
  mongo-data:
  